# determiner_agent.py

from google.adk.agents import LlmAgent
from tools import exit_loop

Determiner = LlmAgent(
    name="Determiner",
    model="gemini-2.5-flash",
    description=(
        "Validates the HTML code generated by Creator. "
        "If the code is incorrect or incomplete, returns instructions in {instruct} "
        "to fix the code. Once the boilerplate is correct, provides detailed step-by-step instructions "
        "from the {section_plan} to add sections into the HTML. "
        "After all sections are completed, performs a final refinement pass to ensure clean, valid, and optimized HTML. "
        "Finally, it calls the exit_loop tool when everything is complete."
    ),
    instruction=(
        "Step 1: Review the state {generated_code}.\n"
        "  - Check for valid HTML boilerplate: <!DOCTYPE html>, <html>, <head>, <body>, and empty <script> tag at the end.\n"
        "  - Ensure <title> and meta tags are present and use {web_info_output} and {problem_config} for relevant info.\n"
        "  - Ensure placeholders/divs exist for sections as per {section_plan}.\n"
        "  - Ensure all CSS is inline.\n\n"
        
        "Step 2: If any issues are found in the boilerplate:\n"
        "  - Populate state {instruct} with precise instructions for Creator to fix the code.\n"
        "  - Do NOT modify {generated_code} yourself.\n\n"
        
        "Step 3: If boilerplate is correct:\n"
        "  - Review {section_plan} and determine the section that needs to be added.\n"
        "  - Provide detailed instructions in state {instruct} for Creator to generate that section, "
        "    including any relevant info from {web_info_output} and {problem_config}.\n"
        "  - Ensure instructions mention inline CSS and placement of elements, but Creator keeps main <script> at the end.\n"
        "  - Only include content relevant to the webpage; do not invent unrelated sections or features.\n\n"
        
        "Step 4: Continue this loop until all sections from {section_plan} are added.\n"
        "  - After each section, update the state {generated_code} via Creator.\n"
        "  - Repeat Step 3 for the next section.\n\n"
        
        "Step 5 (Refinement Pass): Once all sections are added:\n"
        "  - Carefully review the full {generated_code} for:\n"
        "    • Correct and consistent indentation/formatting.\n"
        "    • Closing tags (<div>, <section>, <body>, <html>, etc.) are properly matched.\n"
        "    • No duplicate or redundant inline CSS.\n"
        "    • Metadata in <head> matches context from {problem_config} and {web_info_output}.\n"
        "    • Accessibility basics (alt text for images, semantic tags where possible).\n"
        "  - If refinement is needed, populate {instruct} with clear corrections for Creator.\n\n"
        
        "Step 6: If refinement is complete and no issues remain:\n"
        "  - Call the exit_loop tool to stop the generation loop."
    ),
    sub_agents=[],
    tools=[exit_loop]
)
